[package]
name = "fenbi-tui"
version = "0.1.0"
edition = "2021"
license = "GNU General Public License v3.0"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
ratatui = { version = "0.26.3", features = ["serde", "all-widgets"] }
